// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterScopedOwner) DeepCopyInto(out *ClusterScopedOwner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterScopedOwner.
func (in *ClusterScopedOwner) DeepCopy() *ClusterScopedOwner {
	if in == nil {
		return nil
	}
	out := new(ClusterScopedOwner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterScopedOwner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterScopedOwnerList) DeepCopyInto(out *ClusterScopedOwnerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterScopedOwner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterScopedOwnerList.
func (in *ClusterScopedOwnerList) DeepCopy() *ClusterScopedOwnerList {
	if in == nil {
		return nil
	}
	out := new(ClusterScopedOwnerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterScopedOwnerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterScopedOwnerSpec) DeepCopyInto(out *ClusterScopedOwnerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterScopedOwnerSpec.
func (in *ClusterScopedOwnerSpec) DeepCopy() *ClusterScopedOwnerSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterScopedOwnerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterScopedOwnerStatus) DeepCopyInto(out *ClusterScopedOwnerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterScopedOwnerStatus.
func (in *ClusterScopedOwnerStatus) DeepCopy() *ClusterScopedOwnerStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterScopedOwnerStatus)
	in.DeepCopyInto(out)
	return out
}
